from dataclasses import dataclass
from ...domain.entities.annotation import (
    ANNOTATION_TYPE_ARROW,
    ANNOTATION_TYPE_CLOUD,
    ANNOTATION_TYPE_DIMENSION,
    ANNOTATION_TYPE_HIGHLIGHT,
    ANNOTATION_TYPE_HOTLINK,
    ANNOTATION_TYPE_INK,
    ANNOTATION_TYPE_LINE,
    ANNOTATION_TYPE_NAMED_VIEW,
    ANNOTATION_TYPE_OVAL,
    ANNOTATION_TYPE_POLYGON,
    ANNOTATION_TYPE_RECT,
    ANNOTATION_TYPE_TEXT,
)
from ..config import (
    ACTION_ARROW_ANNOTATION_LABEL,
    ACTION_ARROW_ANNOTATION_TOOLTIP,
    ACTION_CLOUD_ANNOTATION_LABEL,
    ACTION_CLOUD_ANNOTATION_TOOLTIP,
    ACTION_DIMENSION_LABEL,
    ACTION_DIMENSION_TOOLTIP,
    ACTION_HIGHLIGHT_ANNOTATION_LABEL,
    ACTION_HIGHLIGHT_ANNOTATION_TOOLTIP,
    ACTION_HOTLINK_LABEL,
    ACTION_HOTLINK_TOOLTIP,
    ACTION_INK_ANNOTATION_LABEL,
    ACTION_INK_ANNOTATION_TOOLTIP,
    ACTION_LINE_ANNOTATION_LABEL,
    ACTION_LINE_ANNOTATION_TOOLTIP,
    ACTION_NAMED_VIEW_LABEL,
    ACTION_NAMED_VIEW_TOOLTIP,
    ACTION_OVAL_ANNOTATION_LABEL,
    ACTION_OVAL_ANNOTATION_TOOLTIP,
    ACTION_PAN_LABEL,
    ACTION_PAN_TOOLTIP,
    ACTION_PLACE_LABEL,
    ACTION_PLACE_TOOLTIP,
    ACTION_POLYGON_ANNOTATION_LABEL,
    ACTION_POLYGON_ANNOTATION_TOOLTIP,
    ACTION_RECTANGLE_ANNOTATION_LABEL,
    ACTION_RECTANGLE_ANNOTATION_TOOLTIP,
    ACTION_SELECT_LABEL,
    ACTION_SELECT_TOOLTIP,
    ACTION_TEXT_ANNOTATION_LABEL,
    ACTION_TEXT_ANNOTATION_TOOLTIP,
    ACTION_ZOOM_LABEL,
    ACTION_ZOOM_TOOLTIP,
)
from ..managers.icon_manager import IconId


@dataclass(frozen=True)
class PlanToolSpec:
    action_key: str
    label: str
    tooltip: str
    icon_id: IconId
    annotation_type: str | None = None


PLAN_CURSOR_TOOL_SPECS = (
    PlanToolSpec(
        IconId.SELECT_TOOL.value,
        ACTION_SELECT_LABEL,
        ACTION_SELECT_TOOLTIP,
        IconId.SELECT_TOOL,
    ),
    PlanToolSpec(
        IconId.PLACE_TOOL.value,
        ACTION_PLACE_LABEL,
        ACTION_PLACE_TOOLTIP,
        IconId.PLACE_TOOL,
    ),
    PlanToolSpec(
        IconId.PAN_TOOL.value,
        ACTION_PAN_LABEL,
        ACTION_PAN_TOOLTIP,
        IconId.PAN_TOOL,
    ),
    PlanToolSpec(
        IconId.ZOOM_TOOL.value,
        ACTION_ZOOM_LABEL,
        ACTION_ZOOM_TOOLTIP,
        IconId.ZOOM_TOOL,
    ),
)
PLAN_ANNOTATION_TOOL_SPECS = (
    PlanToolSpec(
        IconId.DIMENSION_TOOL.value,
        ACTION_DIMENSION_LABEL,
        ACTION_DIMENSION_TOOLTIP,
        IconId.DIMENSION_TOOL,
        annotation_type=ANNOTATION_TYPE_DIMENSION,
    ),
    PlanToolSpec(
        IconId.TEXT_ANNOTATION_TOOL.value,
        ACTION_TEXT_ANNOTATION_LABEL,
        ACTION_TEXT_ANNOTATION_TOOLTIP,
        IconId.TEXT_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_TEXT,
    ),
    PlanToolSpec(
        IconId.HIGHLIGHT_ANNOTATION_TOOL.value,
        ACTION_HIGHLIGHT_ANNOTATION_LABEL,
        ACTION_HIGHLIGHT_ANNOTATION_TOOLTIP,
        IconId.HIGHLIGHT_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_HIGHLIGHT,
    ),
    PlanToolSpec(
        IconId.ARROW_ANNOTATION_TOOL.value,
        ACTION_ARROW_ANNOTATION_LABEL,
        ACTION_ARROW_ANNOTATION_TOOLTIP,
        IconId.ARROW_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_ARROW,
    ),
    PlanToolSpec(
        IconId.LINE_ANNOTATION_TOOL.value,
        ACTION_LINE_ANNOTATION_LABEL,
        ACTION_LINE_ANNOTATION_TOOLTIP,
        IconId.LINE_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_LINE,
    ),
    PlanToolSpec(
        IconId.RECTANGLE_ANNOTATION_TOOL.value,
        ACTION_RECTANGLE_ANNOTATION_LABEL,
        ACTION_RECTANGLE_ANNOTATION_TOOLTIP,
        IconId.RECTANGLE_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_RECT,
    ),
    PlanToolSpec(
        IconId.OVAL_ANNOTATION_TOOL.value,
        ACTION_OVAL_ANNOTATION_LABEL,
        ACTION_OVAL_ANNOTATION_TOOLTIP,
        IconId.OVAL_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_OVAL,
    ),
    PlanToolSpec(
        IconId.POLYGON_ANNOTATION_TOOL.value,
        ACTION_POLYGON_ANNOTATION_LABEL,
        ACTION_POLYGON_ANNOTATION_TOOLTIP,
        IconId.POLYGON_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_POLYGON,
    ),
    PlanToolSpec(
        IconId.CLOUD_ANNOTATION_TOOL.value,
        ACTION_CLOUD_ANNOTATION_LABEL,
        ACTION_CLOUD_ANNOTATION_TOOLTIP,
        IconId.CLOUD_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_CLOUD,
    ),
    PlanToolSpec(
        IconId.INK_ANNOTATION_TOOL.value,
        ACTION_INK_ANNOTATION_LABEL,
        ACTION_INK_ANNOTATION_TOOLTIP,
        IconId.INK_ANNOTATION_TOOL,
        annotation_type=ANNOTATION_TYPE_INK,
    ),
    PlanToolSpec(
        IconId.HOTLINK_TOOL.value,
        ACTION_HOTLINK_LABEL,
        ACTION_HOTLINK_TOOLTIP,
        IconId.HOTLINK_TOOL,
        annotation_type=ANNOTATION_TYPE_HOTLINK,
    ),
    PlanToolSpec(
        IconId.NAMED_VIEW_TOOL.value,
        ACTION_NAMED_VIEW_LABEL,
        ACTION_NAMED_VIEW_TOOLTIP,
        IconId.NAMED_VIEW_TOOL,
        annotation_type=ANNOTATION_TYPE_NAMED_VIEW,
    ),
)
PLAN_TOOL_SPECS = PLAN_CURSOR_TOOL_SPECS + PLAN_ANNOTATION_TOOL_SPECS
PLAN_TOOL_ACTION_KEYS = tuple(spec.action_key for spec in PLAN_TOOL_SPECS)
PLAN_TOOL_MENU_ITEMS = tuple(("shared", spec.action_key) for spec in PLAN_TOOL_SPECS)
PLAN_TOOL_CONTEXT_ACTIONS = tuple(
    (spec.label, spec.action_key) for spec in PLAN_TOOL_SPECS
)
