CURSOR_MODE_DEFAULT = "default"
CURSOR_MODE_SELECT = "select"
CURSOR_MODE_PLACE = "place"
CURSOR_MODE_ANNOTATION_PLACE = "annotation_place"
CURSOR_MODE_PAN = "pan"
CURSOR_MODE_ZOOM = "zoom"
CURSOR_MODE_ROTATE = "rotate"
CURSOR_MODE_SLOPE_ROTATE = "slope_rotate"
CURSOR_MODE_PASTE_BACKOUT = "paste_backout"
CURSOR_MODE_MOVE_OVERLAY = "move_overlay"
CURSOR_MODE_MOVE_OVERLAY_HANDLE = "move_overlay_handle"
PASSIVE_MOUSE_TRACKING_CURSOR_MODES = frozenset(
    {
        CURSOR_MODE_SELECT,
        CURSOR_MODE_PLACE,
        CURSOR_MODE_ANNOTATION_PLACE,
        CURSOR_MODE_PASTE_BACKOUT,
        CURSOR_MODE_ROTATE,
        CURSOR_MODE_SLOPE_ROTATE,
        CURSOR_MODE_MOVE_OVERLAY_HANDLE,
        CURSOR_MODE_MOVE_OVERLAY,
    }
)
