"""Reference Access schema metadata for newly created OST databases."""

UID_REQUIRED_TABLES = (
    "AccessLevels",
    "AffectDPCTypGroupViews",
    "BidALines",
    "BidAnnoInk",
    "BidAnnotationClouds",
    "BidAnnotationOvals",
    "BidAnnotationPolygons",
    "BidAnnotationRects",
    "BidAreas",
    "BidAreaTranslations",
    "BidArrows",
    "BidCallOuts",
    "BidComments",
    "BidConditionFolders",
    "BidConditions",
    "BidConditionUser",
    "BidDimensions",
    "BidDPCSubscribers",
    "BidEmployees",
    "BidHighlights",
    "BidHotLinks",
    "BidLaborActivity",
    "BidLaborCostCodes",
    "BidLaborCostCodeTotals",
    "BidLayers",
    "BidLegends",
    "BidMarkedPages",
    "BidNamedViews",
    "BidNotes",
    "BidPageFolders",
    "BidPages",
    "BidPageSettings",
    "BidPercents",
    "BidPlanRooms",
    "BidProjects",
    "Bids",
    "BidSettings",
    "BidTakeoffs",
    "BidTakeoffTotals",
    "BidTexts",
    "BidTimeCards",
    "BidTimeCardStates",
    "BidTransactionsHistory",
    "BidTypAreaCounts",
    "BidTypAreas",
    "BidTypGroupViews",
    "BidTypicalGroupTotals",
    "BidZones",
    "Boost",
    "CdnTypes",
    "ConditionSets",
    "ConditionSetStyles",
    "CostCodes",
    "DPCCalcFilter",
    "Employees",
    "JobStatuses",
    "Locking",
    "OCRProps",
    "PayClasses",
    "SchemaRegistry",
    "Settings",
    "STSTransactionHistory",
    "Transactions",
    "UserMasterConditions",
)
FIELD_DEFAULTS = {
    ("BidALines", "Color"): "0",
    ("BidAnnoInk", "Color"): "0",
    ("BidAnnotationClouds", "Color"): "0",
    ("BidAnnotationOvals", "Color"): "0",
    ("BidAnnotationPolygons", "Color"): "0",
    ("BidAnnotationRects", "Color"): "0",
    ("BidAreas", "Sequence"): "0",
    ("BidArrows", "Color"): "0",
    ("BidCallOuts", "FontColor"): "0",
    ("BidCallOuts", "Color"): "0",
    ("BidComments", "Color"): "0",
    ("BidConditions", "Spacing"): "0",
    ("BidDimensions", "FontColor"): "0",
    ("BidHighlights", "Color"): "0",
    ("BidHotLinks", "BidPageViewUID"): "0",
    ("BidHotLinks", "Color"): "0",
    ("BidLaborActivity", "RuleValue"): "0",
    ("BidLaborCostCodes", "Type"): "0",
    ("BidLegends", "FontColor"): "0",
    ("BidPages", "DigitizerNX1"): "0",
    ("BidPages", "DigitizerNY1"): "0",
    ("BidPages", "DigitizerNX2"): "0",
    ("BidPages", "DigitizerNY2"): "0",
    ("BidPages", "DigitizerWidth"): "0",
    ("BidPages", "DigitizerHeight"): "0",
    ("BidPages", "DigitizerResX"): "0",
    ("BidPages", "DigitizerResY"): "0",
    ("Bids", "ExternalID"): "0",
    ("Bids", "HoursPerDay"): "0",
    ("Bids", "MeasureBase"): "0",
    ("Bids", "WeekStartDay"): "0",
    ("Bids", "DPCMode"): "0",
    ("Bids", "IsDPCUpdated"): "0",
    ("Bids", "IgnoreBidAreas"): "0",
    ("Bids", "SendImageFiles"): "0",
    ("Bids", "HasSTSClash"): "0",
    ("Bids", "SRPending"): "0",
    ("Bids", "IsUnlocked"): "0",
    ("Bids", "FullBidSent"): "0",
    ("BidTakeoffs", "Count"): "0",
    ("BidTakeoffs", "GridOffsetX"): "0",
    ("BidTakeoffs", "GridOffsetY"): "0",
    ("BidTakeoffs", "GridRotation"): "0",
    ("BidTakeoffs", "IsNegativeQuantity"): "0",
    ("BidTakeoffs", "FontColor"): "0",
    ("BidTakeoffs", "NameFontColor"): "0",
    ("BidTexts", "FontColor"): "0",
    ("BidTransactionsHistory", "TransactionID"): "0",
    ("BidTypAreas", "Sequence"): "0",
    ("CostCodes", "Sequence"): "0",
    ("CostCodes", "RuleValue"): "0",
    ("Settings", "QuantitiesInLegend"): "0",
    ("Settings", "HoursPerDay"): "0",
    ("Settings", "StartWeekOn"): "0",
    ("Settings", "GridCountMethod"): "0",
    ("Settings", "IgnoreBidAreas"): "0",
    ("Settings", "SendImageFiles"): "0",
    ("Settings", "BackupNo"): "2",
    ("Settings", "BackupPeriod"): "2",
    ("Settings", "CompressPeriod"): "3",
    ("STSTransactionHistory", "ChangeType"): "0",
}
EXPLICIT_INDEXES = (
    ("AffectDPCTypGroupViews", "AffectDPCTypGroupViews_BidUID", False, ("BidUID",)),
    ("BidALines", "BidALines_BidPageUID", False, ("BidPageUID",)),
    ("BidALines", "BidALines_BidTakeoffFromUID", False, ("BidTakeoffFromUID",)),
    ("BidALines", "BidALines_BidTakeoffToUID", False, ("BidTakeoffToUID",)),
    ("BidALines", "BidALines_BidUID", False, ("BidUID",)),
    ("BidAnnoInk", "BidAnnoInk_BidPageUID", False, ("BidPageUID",)),
    ("BidAnnoInk", "BidAnnoInk_BidUID", False, ("BidUID",)),
    ("BidAnnotationClouds", "BidAnnotationClouds_BidPageUID", False, ("BidPageUID",)),
    ("BidAnnotationClouds", "BidAnnotationClouds_BidUID", False, ("BidUID",)),
    ("BidAnnotationClouds", "BidAnnotationClouds_LayerUID", False, ("BidLayerUID",)),
    ("BidAnnotationOvals", "BidAnnotationOvals_BidPageUID", False, ("BidPageUID",)),
    ("BidAnnotationOvals", "BidAnnotationOvals_BidUID", False, ("BidUID",)),
    ("BidAnnotationOvals", "BidAnnotationOvals_LayerUID", False, ("BidLayerUID",)),
    (
        "BidAnnotationPolygons",
        "BidAnnotationPolygons_BidPageUID",
        False,
        ("BidPageUID",),
    ),
    ("BidAnnotationPolygons", "BidAnnotationPolygons_BidUID", False, ("BidUID",)),
    (
        "BidAnnotationPolygons",
        "BidAnnotationPolygons_LayerUID",
        False,
        ("BidLayerUID",),
    ),
    ("BidAnnotationRects", "BidAnnotationRects_BidPageUID", False, ("BidPageUID",)),
    ("BidAnnotationRects", "BidAnnotationRects_BidUID", False, ("BidUID",)),
    ("BidAnnotationRects", "BidAnnotationRects_LayerUID", False, ("BidLayerUID",)),
    ("BidAreas", "BidAreas_BidUID", False, ("BidUID",)),
    ("BidAreas", "BidAreas_GUID", False, ("GUID",)),
    ("BidAreas", "BidAreas_ParentUID", False, ("ParentUID",)),
    ("BidAreaTranslations", "BidAreaTranslations_BidPageUID", False, ("BidPageUID",)),
    ("BidArrows", "BidArrows_BidPageUID", False, ("BidPageUID",)),
    ("BidArrows", "BidArrows_BidTakeoffFromUID", False, ("BidTakeoffFromUID",)),
    ("BidArrows", "BidArrows_BidTakeoffToUID", False, ("BidTakeoffToUID",)),
    ("BidArrows", "BidArrows_BidUID", False, ("BidUID",)),
    ("BidCallOuts", "BidCallOuts_BidPageUID", False, ("BidPageUID",)),
    ("BidCallOuts", "BidCallOuts_BidUID", False, ("BidUID",)),
    ("BidCallOuts", "BidCallOuts_LayerUID", False, ("BidLayerUID",)),
    ("BidComments", "BidComments_BidPageUID", False, ("BidPageUID",)),
    ("BidComments", "BidComments_BidUID", False, ("BidUID",)),
    ("BidComments", "BidComments_LayerUID", False, ("BidLayerUID",)),
    ("BidComments", "BidComments_ParentUID", False, ("ParentCommentUID",)),
    ("BidConditionFolders", "BidConditionFolders_BidUID", False, ("BidUID",)),
    ("BidConditionFolders", "BidConditionFolders_ParentUID", False, ("ParentUID",)),
    (
        "BidConditions",
        "BidConditions_BidConditionFolderUID",
        False,
        ("BidConditionFolderUID",),
    ),
    ("BidConditions", "BidConditions_BidLayerUID", False, ("BidLayerUID",)),
    ("BidConditions", "BidConditions_BidUID", False, ("BidUID",)),
    ("BidDimensions", "BidDimensions_BidPageUID", False, ("BidPageUID",)),
    ("BidDimensions", "BidDimensions_BidTakeoffFromUID", False, ("BidTakeoffFromUID",)),
    ("BidDimensions", "BidDimensions_BidTakeoffToUID", False, ("BidTakeoffToUID",)),
    ("BidDimensions", "BidDimensions_BidUID", False, ("BidUID",)),
    (
        "BidDPCSubscribers",
        "BidDPCSubscribers_BidEmployeeUID",
        False,
        ("BidEmployeeUID",),
    ),
    ("BidDPCSubscribers", "BidDPCSubscribers_BidUID", False, ("BidUID",)),
    ("BidEmployees", "BidEmployees_BidUID", False, ("BidUID",)),
    ("BidEmployees", "BidEmployees_EmployeeUID", False, ("EmployeeUID",)),
    ("BidEmployees", "BidEmployees_GUID", False, ("GUID",)),
    ("BidHighlights", "BidHighlights_BidLayerUID", False, ("BidLayerUID",)),
    ("BidHighlights", "BidHighlights_BidPageUID", False, ("BidPageUID",)),
    ("BidHighlights", "BidHighlights_BidUID", False, ("BidUID",)),
    ("BidHotLinks", "BidHotLinks_BidLayerUID", False, ("BidLayerUID",)),
    ("BidHotLinks", "BidHotLinks_BidPageUID", False, ("BidPageUID",)),
    ("BidHotLinks", "BidHotLinks_BidPageViewUID", False, ("BidPageViewUID",)),
    ("BidHotLinks", "BidHotLinks_BidUID", False, ("BidUID",)),
    (
        "BidLaborActivity",
        "BidLaborActivity_BidConditionUID",
        False,
        ("BidConditionUID",),
    ),
    (
        "BidLaborActivity",
        "BidLaborActivity_BidLaborCostCodeUID",
        False,
        ("BidLaborCostCodeUID",),
    ),
    ("BidLaborActivity", "BidLaborActivity_BidUID", False, ("BidUID",)),
    ("BidLaborCostCodes", "BidLaborCostCodes_BidUID", False, ("BidUID",)),
    ("BidLaborCostCodes", "BidLaborCostCodes_GUID", False, ("GUID",)),
    (
        "BidLaborCostCodeTotals",
        "BidLaborCostCodeTotals_BidPageUID",
        False,
        ("BidPageUID",),
    ),
    ("BidLaborCostCodeTotals", "BidLaborCostCodeTotals_BidUID", False, ("BidUID",)),
    ("BidLayers", "BidLayers_BidUID", False, ("BidUID",)),
    ("BidLayers", "BidLayers_IsTemplateUID", False, ("IsTemplate",)),
    ("BidLegends", "BidLegends_BidPageUID", False, ("BidPageUID",)),
    ("BidLegends", "BidLegends_BidUID", False, ("BidUID",)),
    ("BidNamedViews", "BidNamedViews_BidPageUID", False, ("BidPageUID",)),
    ("BidNamedViews", "BidNamedViews_BidUID", False, ("BidUID",)),
    ("BidNotes", "BidNotes_BidUID", False, ("BidUID",)),
    ("BidNotes", "BidNotes_GUID", False, ("GUID",)),
    ("BidPageFolders", "BidPageFolders_BidUID", False, ("BidUID",)),
    ("BidPageFolders", "BidPageFolders_GUID", False, ("GUID",)),
    ("BidPageFolders", "BidPageFolders_ParentUID", False, ("ParentUID",)),
    ("BidPages", "BidPages_BidPageFolderUID", False, ("BidPageFolderUID",)),
    ("BidPages", "BidPages_BidUID", False, ("BidUID",)),
    ("BidPages", "BidPages_GUID", False, ("GUID",)),
    ("BidPercents", "BidPercents_BidLaborActivityUID", False, ("BidLaborActivityUID",)),
    ("BidPercents", "BidPercents_BidLaborCostCodeUID", False, ("BidLaborCostCodeUID",)),
    ("BidPercents", "BidPercents_BidPageUID", False, ("BidPageUID",)),
    ("BidPercents", "BidPercents_BidTakeoffUID", False, ("BidTakeoffUID",)),
    ("BidPercents", "BidPercents_BidTimeCardStateUID", False, ("BidTimeCardStateUID",)),
    ("BidPercents", "BidPercents_GUID", False, ("GUID",)),
    ("BidPlanRooms", "BidPlanRooms_BidUID", False, ("BidUID",)),
    ("BidProjects", "BidProjects_Name", False, ("Name",)),
    ("Bids", "Bids_BidProjectUID", False, ("BidProjectUID",)),
    ("Bids", "Bids_BidType", False, ("BidType",)),
    ("Bids", "Bids_ParentBidUID", False, ("ParentBidUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidAreaUID", False, ("BidAreaUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidConditionUID", False, ("BidConditionUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidPageUID", False, ("BidPageUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidTypAreaUID", False, ("BidTypAreaUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidUID", False, ("BidUID",)),
    ("BidTakeoffs", "BidTakeoffs_BidZoneUID", False, ("BidZoneUID",)),
    ("BidTakeoffs", "BidTakeoffs_GUID", False, ("GUID",)),
    ("BidTakeoffs", "BidTakeoffs_No", False, ("No",)),
    ("BidTakeoffs", "BidTakeoffs_ParentUID", False, ("ParentUID",)),
    ("BidTakeoffTotals", "BidTakeoffTotals_BidPageUID", False, ("BidPageUID",)),
    ("BidTakeoffTotals", "BidTakeoffTotals_BidUID", False, ("BidUID",)),
    ("BidTexts", "BidTexts_BidPageUID", False, ("BidPageUID",)),
    ("BidTexts", "BidTexts_BidUID", False, ("BidUID",)),
    ("BidTexts", "BidTexts_LayerUID", False, ("BidLayerUID",)),
    ("BidTimeCards", "BidTimeCards_BidAreaUID", False, ("BidAreaUID",)),
    ("BidTimeCards", "BidTimeCards_BidEmployeeUID", False, ("BidEmployeeUID",)),
    (
        "BidTimeCards",
        "BidTimeCards_BidLaborCostCodeUID",
        False,
        ("BidLaborCostCodeUID",),
    ),
    (
        "BidTimeCards",
        "BidTimeCards_BidTimeCardStateUID",
        False,
        ("BidTimeCardStateUID",),
    ),
    ("BidTimeCards", "BidTimeCards_BidTypicalAreaUID", False, ("BidTypicalAreaUID",)),
    ("BidTimeCards", "BidTimeCards_GUID", False, ("GUID",)),
    ("BidTimeCardStates", "BidTimeCardStates_BidUID", False, ("BidUID",)),
    ("BidTimeCardStates", "BidTimeCardStates_GUID", False, ("GUID",)),
    ("BidTransactionsHistory", "BidTransactionsHistory_BidUID", False, ("BidUID",)),
    ("BidTypAreaCounts", "BidTypAreaCounts_BidAreaUID", False, ("BidAreaUID",)),
    ("BidTypAreaCounts", "BidTypAreaCounts_BidTypAreaUID", False, ("BidTypAreaUID",)),
    ("BidTypAreas", "BidTypAreas_BidUID", False, ("BidUID",)),
    ("BidTypGroupViews", "BidTypGroupViews_BidPageUID", False, ("BidPageUID",)),
    ("BidTypGroupViews", "BidTypGroupViews_BidUID", False, ("BidUID",)),
    (
        "BidTypicalGroupTotals",
        "BidTypicalGroupTotals_BidPageUID",
        False,
        ("BidPageUID",),
    ),
    ("BidTypicalGroupTotals", "BidTypicalGroupTotals_BidUID", False, ("BidUID",)),
    ("BidZones", "BidZones_BidLayerUID", False, ("BidLayerUID",)),
    ("BidZones", "BidZones_BidUID", False, ("BidUID",)),
    ("CdnTypes", "CdnTypes_Name", False, ("Name",)),
    (
        "ConditionSetStyles",
        "ConditionSetStyles_ConditionSetUID",
        False,
        ("ConditionSetUID",),
    ),
    (
        "ConditionSetStyles",
        "ConditionSetStyles_ConditionStyleUID",
        False,
        ("ConditionStyleUID",),
    ),
    ("DPCCalcFilter", "DPCCalcFilter_BidUID", False, ("BidUID",)),
    ("Employees", "Employees_AccessLevelUID", False, ("AccessLevelUID",)),
    ("Employees", "Employees_LoginName", False, ("LoginName",)),
    ("Employees", "Employees_PayClassUID", False, ("PayClassUID",)),
    ("Locking", "UI_Locking", True, ("Essence", "Owner")),
    ("Locking", "UI_Locking2", True, ("Essence",)),
    (
        "STSTransactionHistory",
        "STSTransactionHistory_ChangeType",
        False,
        ("ChangeType",),
    ),
    ("STSTransactionHistory", "STSTransactionHistory_ObjectUID", False, ("ObjectUID",)),
    ("UserMasterConditions", "UserMasterConditions_Name", False, ("Name",)),
)
REFERENCE_RELATIONSHIPS = (
    ("BidALines_BidPageUID1", "BidALines", "BidPageUID", "BidPages", "UID"),
    (
        "BidALines_BidTakeoffFromUID1",
        "BidALines",
        "BidTakeoffFromUID",
        "BidTakeoffs",
        "UID",
    ),
    ("BidALines_BidUID1", "BidALines", "BidUID", "Bids", "UID"),
    ("BidAnnoInk_BidPageUID1", "BidAnnoInk", "BidPageUID", "BidPages", "UID"),
    ("BidAreas_BidUID1", "BidAreas", "BidUID", "Bids", "UID"),
    ("BidArrows_BidPageUID1", "BidArrows", "BidPageUID", "BidPages", "UID"),
    (
        "BidArrows_BidTakeoffFromUID1",
        "BidArrows",
        "BidTakeoffFromUID",
        "BidTakeoffs",
        "UID",
    ),
    ("BidArrows_BidUID1", "BidArrows", "BidUID", "Bids", "UID"),
    ("BidCallOuts_BidLayerUID1", "BidCallOuts", "BidLayerUID", "BidLayers", "UID"),
    ("BidCallOuts_BidPageUID1", "BidCallOuts", "BidPageUID", "BidPages", "UID"),
    ("BidCallOuts_BidUID1", "BidCallOuts", "BidUID", "Bids", "UID"),
    ("BidConditionFolders_BidUID1", "BidConditionFolders", "BidUID", "Bids", "UID"),
    (
        "BidConditions_BidConditionFolderUID1",
        "BidConditions",
        "BidConditionFolderUID",
        "BidConditionFolders",
        "UID",
    ),
    ("BidConditions_BidLayerUID1", "BidConditions", "BidLayerUID", "BidLayers", "UID"),
    ("BidConditions_BidUID1", "BidConditions", "BidUID", "Bids", "UID"),
    ("BidConditions_CdnTypeUID1", "BidConditions", "CdnTypeUID", "CdnTypes", "UID"),
    ("BidDimensions_BidPageUID1", "BidDimensions", "BidPageUID", "BidPages", "UID"),
    (
        "BidDimensions_BidTakeoffFromUID1",
        "BidDimensions",
        "BidTakeoffFromUID",
        "BidTakeoffs",
        "UID",
    ),
    ("BidDimensions_BidUID1", "BidDimensions", "BidUID", "Bids", "UID"),
    (
        "BidDPCSubscribers_BidEmployeeUID1",
        "BidDPCSubscribers",
        "BidEmployeeUID",
        "Employees",
        "UID",
    ),
    ("BidDPCSubscribers_BidUID1", "BidDPCSubscribers", "BidUID", "Bids", "UID"),
    ("BidEmployees_BidUID1", "BidEmployees", "BidUID", "Bids", "UID"),
    ("BidEmployees_EmployeeUID1", "BidEmployees", "EmployeeUID", "Employees", "UID"),
    ("BidEmployees_PayClassUID1", "BidEmployees", "PayClassUID", "PayClasses", "UID"),
    ("BidHighlights_BidLayerUID1", "BidHighlights", "BidLayerUID", "BidLayers", "UID"),
    ("BidHighlights_BidPageUID1", "BidHighlights", "BidPageUID", "BidPages", "UID"),
    ("BidHighlights_BidUID1", "BidHighlights", "BidUID", "Bids", "UID"),
    ("BidHotLinks_BidLayerUID1", "BidHotLinks", "BidLayerUID", "BidLayers", "UID"),
    ("BidHotLinks_BidPageUID1", "BidHotLinks", "BidPageUID", "BidPages", "UID"),
    (
        "BidHotLinks_BidPageViewUID1",
        "BidHotLinks",
        "BidPageViewUID",
        "BidNamedViews",
        "UID",
    ),
    ("BidHotLinks_BidUID1", "BidHotLinks", "BidUID", "Bids", "UID"),
    (
        "BidLaborActivity_BidConditionUID1",
        "BidLaborActivity",
        "BidConditionUID",
        "BidConditions",
        "UID",
    ),
    (
        "BidLaborActivity_BidLaborCostCodeUID1",
        "BidLaborActivity",
        "BidLaborCostCodeUID",
        "BidLaborCostCodes",
        "UID",
    ),
    ("BidLaborActivity_BidUID1", "BidLaborActivity", "BidUID", "Bids", "UID"),
    ("BidLaborCostCodes_BidUID1", "BidLaborCostCodes", "BidUID", "Bids", "UID"),
    (
        "BidLaborCostCodes_CostCodeUID1",
        "BidLaborCostCodes",
        "CostCodeUID",
        "CostCodes",
        "UID",
    ),
    ("BidLayers_BidUID1", "BidLayers", "BidUID", "Bids", "UID"),
    ("BidLegends_BidPageUID1", "BidLegends", "BidPageUID", "BidPages", "UID"),
    ("BidLegends_BidUID1", "BidLegends", "BidUID", "Bids", "UID"),
    ("BidNamedViews_BidPageUID1", "BidNamedViews", "BidPageUID", "BidPages", "UID"),
    ("BidNamedViews_BidUID1", "BidNamedViews", "BidUID", "Bids", "UID"),
    ("BidNotes_Bids1", "BidNotes", "BidUID", "Bids", "UID"),
    ("BidPageFolders_BidUID1", "BidPageFolders", "BidUID", "Bids", "UID"),
    (
        "BidPages_BidPageFolderUID1",
        "BidPages",
        "BidPageFolderUID",
        "BidPageFolders",
        "UID",
    ),
    ("BidPages_BidUID1", "BidPages", "BidUID", "Bids", "UID"),
    ("BidPageSettings_BidAreaUID1", "BidPageSettings", "BidAreaUID", "BidAreas", "UID"),
    ("BidPageSettings_BidPageUID1", "BidPageSettings", "BidPageUID", "BidPages", "UID"),
    (
        "BidPageSettings_BidTypAreaUID1",
        "BidPageSettings",
        "BidTypAreaUID",
        "BidTypAreas",
        "UID",
    ),
    (
        "BidPercents_BidLaborCostCodeUID1",
        "BidPercents",
        "BidLaborCostCodeUID",
        "BidLaborCostCodes",
        "UID",
    ),
    (
        "BidPercents_BidTakeoffUID1",
        "BidPercents",
        "BidTakeoffUID",
        "BidTakeoffs",
        "UID",
    ),
    (
        "BidPercents_BidTimeCardStateUID1",
        "BidPercents",
        "BidTimeCardStateUID",
        "BidTimeCardStates",
        "UID",
    ),
    ("BidPlanrooms_BidUID1", "BidPlanrooms", "BidUID", "Bids", "UID"),
    ("Bids_BidProjectUID1", "Bids", "BidProjectUID", "BidProjects", "UID"),
    (
        "BidSettings_BidPageSelectedUID1",
        "BidSettings",
        "BidPageSelectedUID",
        "BidPages",
        "UID",
    ),
    ("BidTakeoffs_BidAreaUID1", "BidTakeoffs", "BidAreaUID", "BidAreas", "UID"),
    (
        "BidTakeoffs_BidConditionUID1",
        "BidTakeoffs",
        "BidConditionUID",
        "BidConditions",
        "UID",
    ),
    ("BidTakeoffs_BidPageUID1", "BidTakeoffs", "BidPageUID", "BidPages", "UID"),
    (
        "BidTakeoffs_BidTypAreaUID1",
        "BidTakeoffs",
        "BidTypAreaUID",
        "BidTypAreas",
        "UID",
    ),
    ("BidTakeoffs_BidZoneUID1", "BidTakeoffs", "BidZoneUID", "BidZones", "UID"),
    (
        "BidTakeoffTotals_BidPageUID1",
        "BidTakeoffTotals",
        "BidPageUID",
        "BidPages",
        "UID",
    ),
    ("BidTakeoffTotals_BidUID1", "BidTakeoffTotals", "BidUID", "Bids", "UID"),
    ("BidTexts_BidLayerUID1", "BidTexts", "BidLayerUID", "BidLayers", "UID"),
    ("BidTexts_BidPageUID1", "BidTexts", "BidPageUID", "BidPages", "UID"),
    ("BidTexts_BidUID1", "BidTexts", "BidUID", "Bids", "UID"),
    ("BidTimeCards_BidAreaUID1", "BidTimeCards", "BidAreaUID", "BidAreas", "UID"),
    (
        "BidTimeCards_BidEmployeeUID1",
        "BidTimeCards",
        "BidEmployeeUID",
        "BidEmployees",
        "UID",
    ),
    (
        "BidTimeCards_BidLaborCostCodeUID1",
        "BidTimeCards",
        "BidLaborCostCodeUID",
        "BidLaborCostCodes",
        "UID",
    ),
    (
        "BidTimeCards_BidTimeCardStateUID1",
        "BidTimeCards",
        "BidTimeCardStateUID",
        "BidTimeCardStates",
        "UID",
    ),
    (
        "BidTimeCards_BidTypicalAreaUID1",
        "BidTimeCards",
        "BidTypicalAreaUID",
        "BidTypAreas",
        "UID",
    ),
    ("BidTimeCardStates_BidUID1", "BidTimeCardStates", "BidUID", "Bids", "UID"),
    (
        "BidTransactionsHistory_BidUID1",
        "BidTransactionsHistory",
        "BidUID",
        "Bids",
        "UID",
    ),
    (
        "BidTypAreaCounts_BidAreaUID1",
        "BidTypAreaCounts",
        "BidAreaUID",
        "BidAreas",
        "UID",
    ),
    (
        "BidTypAreaCounts_BidTypAreaUID1",
        "BidTypAreaCounts",
        "BidTypAreaUID",
        "BidTypAreas",
        "UID",
    ),
    ("BidTypAreas_BidUID1", "BidTypAreas", "BidUID", "Bids", "UID"),
    (
        "BidTypicalGroupTotals_BidPageUID1",
        "BidTypicalGroupTotals",
        "BidPageUID",
        "BidPages",
        "UID",
    ),
    ("BidTypicalGroupTotals_BidUID1", "BidTypicalGroupTotals", "BidUID", "Bids", "UID"),
    ("BidZones_BidLayerUID1", "BidZones", "BidLayerUID", "BidLayers", "UID"),
    ("BidZones_BidUID1", "BidZones", "BidUID", "Bids", "UID"),
    ("ConditionSets_EmployeeUID1", "ConditionSets", "EmployeeUID", "Employees", "UID"),
    (
        "ConditionSetStyles_ConditionSetUID1",
        "ConditionSetStyles",
        "ConditionSetUID",
        "ConditionSets",
        "UID",
    ),
    (
        "ConditionSetStyles_ConditionStyleUID1",
        "ConditionSetStyles",
        "ConditionStyleUID",
        "BidConditions",
        "UID",
    ),
    ("Employees_AccessLevelUID1", "Employees", "AccessLevelUID", "AccessLevels", "UID"),
    ("Employees_PayClassUID1", "Employees", "PayClassUID", "PayClasses", "UID"),
)
