[network]
forceencryption = 1
tlscert = /var/opt/mssql/tls/server.pem
tlskey = /var/opt/mssql/tls/server.key
tlsprotocols = 1.2

[filelocation]
defaultbackupdir = /var/opt/mssql/backup

[memory]
enablecontainersharedmemory = true
