from typing import Any, Optional, Protocol
from PySide6 import QtCore, QtGui, QtWidgets
from ...domain.entities.annotation_style import AnnotationStyle


class IWorkspaceShell(Protocol):
    takeoff_sidebar: Any

    def installEventFilter(self, _filter_obj: QtCore.QObject) -> None: ...
    def restoreGeometry(self, geometry: QtCore.QByteArray) -> bool: ...
    def restoreState(self, state: QtCore.QByteArray, version: int = 0) -> bool: ...
    def saveGeometry(self) -> QtCore.QByteArray: ...
    def saveState(self, version: int = 0) -> QtCore.QByteArray: ...
    def show(self) -> None: ...
    def showMaximized(self) -> None: ...
    def isMaximized(self) -> bool: ...
    def get_workspace_toolbars(self) -> list[QtWidgets.QToolBar]: ...
    def get_project_header(self) -> QtWidgets.QHeaderView: ...
    def get_conditions_sidebar(self) -> Any: ...
    def get_conditions_header(self) -> QtWidgets.QHeaderView: ...
    def get_layers_header(self) -> QtWidgets.QHeaderView: ...
    def get_project_tree(self) -> QtWidgets.QTreeWidget: ...
    def get_view_stack(self) -> QtWidgets.QStackedWidget: ...
    def get_takeoff_splitter(self) -> QtWidgets.QSplitter: ...
    def get_left_splitter(self) -> QtWidgets.QSplitter: ...
    def get_layers_toggle_action(self) -> QtGui.QAction: ...
    def get_conditions_toggle_action(self) -> QtGui.QAction: ...
    def get_mesh_window_action(self) -> QtGui.QAction: ...
    def get_annotation_window_action(self) -> QtGui.QAction: ...
    def get_view_window_action(self) -> QtGui.QAction: ...
    def get_status_bar_action(self) -> QtGui.QAction: ...
    def set_active_takeoff_view(self, active_view: str) -> None: ...
    def get_active_takeoff_view(self) -> str: ...
    def set_takeoff_2d_tab_visible(self, visible: bool) -> None: ...
    def is_takeoff_2d_tab_visible(self) -> bool: ...
    def set_takeoff_3d_tab_visible(self, visible: bool) -> None: ...
    def is_takeoff_3d_tab_visible(self) -> bool: ...
    def set_conditions_sidebar_visible(self, visible: bool) -> None: ...
    def is_conditions_sidebar_visible(self) -> bool: ...
    def set_layers_sidebar_visible(self, visible: bool) -> None: ...
    def is_layers_sidebar_visible(self) -> bool: ...
    def set_status_bar_visible(self, visible: bool) -> None: ...
    def is_status_bar_visible(self) -> bool: ...
    def get_takeoff_splitter_sizes(self) -> list[int]: ...
    def set_takeoff_splitter_sizes(self, sizes: list[int]) -> None: ...
    def get_left_splitter_sizes(self) -> list[int]: ...
    def set_left_splitter_sizes(self, sizes: list[int]) -> None: ...
    def get_workspace_toolbar_visibility_state(self) -> dict[str, bool]: ...
    def set_workspace_toolbar_visibility_state(
        self, state: dict[str, bool]
    ) -> None: ...
    def get_annotation_styles_by_tool(self) -> dict[str, AnnotationStyle]: ...
    def set_annotation_styles_by_tool(
        self,
        styles: dict[str, AnnotationStyle],
        *,
        persist: bool = False,
    ) -> None: ...
    def sync_contextual_shell_visibility(self) -> None: ...
    def is_takeoff_tab_active(self) -> bool: ...
    def get_takeoff_plan_view(self) -> QtWidgets.QWidget: ...
    def get_page_settings_bar(self) -> QtWidgets.QWidget: ...
    def get_takeoff_dropdown_popup_sizes(self) -> dict[str, list[int]]: ...
    def set_takeoff_dropdown_popup_sizes(self, sizes: dict[str, list[int]]) -> None: ...
    def save_project_header_state(self) -> QtCore.QByteArray: ...
    def restore_project_header_state(self, state: QtCore.QByteArray) -> None: ...
    def get_project_expanded_node_keys(self) -> list[str]: ...
    def set_project_expanded_node_keys(self, keys: Optional[list[str]]) -> None: ...
    def is_project_group_by_job_status(self) -> bool: ...
    def set_project_group_by_job_status(self, enabled: bool) -> None: ...
    def get_project_selected_node(self) -> Optional[dict]: ...
    def set_project_selected_node(self, node: Optional[dict]) -> None: ...
    def save_conditions_header_state(self) -> QtCore.QByteArray: ...
    def restore_conditions_header_state(self, state: QtCore.QByteArray) -> None: ...
    def is_conditions_group_by_type_enabled(self) -> bool: ...
    def set_conditions_group_by_type(self, enabled: bool) -> None: ...
    def save_layers_header_state(self) -> QtCore.QByteArray: ...
    def restore_layers_header_state(self, state: QtCore.QByteArray) -> None: ...
    def can_restore_annotation_window(self) -> bool: ...
    def set_annotation_window_visible(
        self,
        visible: bool,
        *,
        initial_geometry: QtCore.QByteArray | None = None,
        initial_is_maximized: bool = True,
        initial_is_fullscreen: bool = False,
    ) -> None: ...
    def is_annotation_window_open(self) -> bool: ...
    def get_annotation_window(self) -> Optional[QtWidgets.QWidget]: ...
    def can_restore_view_window(self) -> bool: ...
    def set_view_window_visible(
        self,
        visible: bool,
        *,
        initial_geometry: QtCore.QByteArray | None = None,
        initial_is_maximized: bool = True,
        initial_is_fullscreen: bool = False,
    ) -> None: ...
    def is_view_window_open(self) -> bool: ...
    def get_view_window(self) -> Optional[QtWidgets.QWidget]: ...
    def set_mesh_window_visible(
        self,
        visible: bool,
        *,
        initial_geometry: QtCore.QByteArray | None = None,
        initial_is_maximized: bool = True,
    ) -> None: ...
    def get_mesh_window(self) -> Optional[QtWidgets.QWidget]: ...
