from typing import List, Optional, Protocol, Tuple, Union
from ...domain.dtos.page_render_info_dto import PageRenderInfo


class ICoordinateTransformer(Protocol):
    @property
    def page_info(self) -> PageRenderInfo: ...
    @property
    def scale_ratio(self) -> float: ...
    def ost_to_real_units(self, ost_coord: float) -> float: ...
    def ost_to_pdf_points(self, ost_coord: float) -> float: ...
    def ost_to_screen_pixels(self, ost_coord: float) -> float: ...
    def pdf_points_to_screen_pixels(self, pdf_points: float) -> float: ...
    def transform_to_2d(self, ost_x: float, ost_y: float) -> Tuple[float, float]: ...
    def transform_to_3d(self, ost_x: float, ost_y: float) -> Tuple[float, float]: ...
    def transform_vertices_to_3d(
        self, vertices: List[Tuple[float, float]]
    ) -> List[Tuple[float, float]]: ...
    def transform_holes_to_3d(
        self, holes: Optional[List[List[Tuple[float, float]]]]
    ) -> Optional[List[List[Tuple[float, float]]]]: ...
    def transform_vertices_to_2d(self, position: List[float]) -> List[float]: ...
    def update_page_info(self, page_info: PageRenderInfo) -> None: ...
    @staticmethod
    def parse_position(position: Union[str, List[float], None]) -> List[float]: ...
    @staticmethod
    def ost_to_pdf_coordinates(
        ost_position: List[float], page_info: PageRenderInfo
    ) -> List[Tuple[float, float]]: ...
