from typing import Optional, Protocol


class ICredentialStore(Protocol):
    def read_password(self, target: str) -> Optional[str]: ...
    def write_password(self, target: str, username: str, password: str) -> None: ...
    def delete_password(self, target: str) -> None: ...
