from typing import Iterable, Optional, Protocol
from ...domain.entities.database_descriptor import DatabaseDescriptor


class IDatabaseDescriptorRegistry(Protocol):
    def register(self, descriptor: DatabaseDescriptor) -> None: ...
    def register_all(self, descriptors: Iterable[DatabaseDescriptor]) -> None: ...
    def resolve(self, locator: str) -> Optional[DatabaseDescriptor]: ...
    def unregister(self, database_id: str) -> None: ...
