from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class DatabaseMaintenanceResult:
    success: bool
    message: str


class IPreparedDatabaseMaintenance(Protocol):
    def commit(self) -> DatabaseMaintenanceResult: ...
    def close(self) -> None: ...
class IDatabaseMaintenance(Protocol):
    # Capturing reserves the source; callers release it on every terminal path.
    def capture_target(self, locator: str) -> object: ...
    def is_target_current(self, locator: str, identity: object) -> bool: ...
    def release_target(self, locator: str, identity: object) -> None: ...
    def prepare(
        self, locator: str, identity: object
    ) -> IPreparedDatabaseMaintenance: ...
    def unavailable_reason(self, locator: str) -> str: ...
    def compact(self, locator: str) -> DatabaseMaintenanceResult: ...
