from typing import Protocol
from ..dtos.collaboration_dtos import ResourceRef


class IDatabaseSessionRegistry(Protocol):
    def register(self, database_id: str, session_id: str) -> None: ...
    def remove(self, database_id: str, session_id: str = "") -> None: ...
    def require(self, database_id: str) -> str: ...
    def get(self, database_id: str) -> str: ...
    def register_lock(
        self, database_id: str, resource: ResourceRef, lock_token: str
    ) -> None: ...
    def remove_lock(self, database_id: str, resource: ResourceRef) -> None: ...
    def lock_tokens(
        self, database_id: str, resources: tuple[ResourceRef, ...]
    ) -> tuple[str, ...]: ...
