from typing import Any, Callable, Optional, Protocol


class ILicenseValidationScheduler(Protocol):
    def set_task(self, task: Callable[[], Optional[Any]]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
