from typing import Any, Dict, List, Optional, Protocol, Set, Tuple
from ...domain.entities.area import BidArea
from ...domain.entities.cdn_type import CdnType
from ...domain.entities.cover_sheet import CoverSheetData, JobStatus
from ...domain.entities.employee import Employee, PayClass
from ...domain.entities.layer import BidLayer


class IMdbReader(Protocol):
    def get_cover_sheet_data(
        self, file_path: str, bid_uid: str
    ) -> Optional[CoverSheetData]: ...
    def get_job_statuses(self, file_path: str) -> List[JobStatus]: ...
    def get_employees_and_pay_classes(
        self, file_path: str
    ) -> Tuple[List[Employee], List[PayClass]]: ...
    def get_bid_areas(self, file_path: str, bid_uid: str) -> List[BidArea]: ...
    def get_cdn_types(self, file_path: str) -> Dict[str, CdnType]: ...
    def get_estimator_uids_in_use(self, file_path: str) -> Set[str]: ...
    def get_condition_type_uids_in_use(self, file_path: str) -> Set[str]: ...
    def get_layer_uids_in_use(self, file_path: str, bid_uid: str) -> Set[str]: ...
    def get_bid_layers_for_sidebar(
        self, file_path: str, bid_uid: str
    ) -> List[BidLayer]: ...
    def get_pages_with_takeoffs(self, file_path: str, bid_uid: str) -> Set[str]: ...
    def get_pages_with_delete_content(
        self, file_path: str, bid_uid: str
    ) -> Set[str]: ...
    def get_settings_defaults(self, file_path: str) -> Dict[str, Any]: ...
