from typing import ContextManager, Protocol


class DatabaseConnectionUnavailableError(RuntimeError):
    """Raised when the database driver cannot create a required connection."""


class IMdbConnectionManager(Protocol):
    def maintenance(self, db_path: str) -> ContextManager[None]: ...
    def set_write_blocked(self, blocked: bool) -> None: ...
    def is_write_blocked(self) -> bool: ...
    def close_write_connections(self) -> None: ...
    def close_database(self, db_path: str) -> None: ...
    def close(self) -> None: ...
