from typing import Protocol


class IMdbConnectionManager(Protocol):
    def set_write_blocked(self, blocked: bool) -> None: ...
    def is_write_blocked(self) -> bool: ...
    def close_write_connections(self) -> None: ...
    def close(self) -> None: ...
