from typing import Any, Callable, Dict, List, Optional, Protocol, Tuple
from ...domain.dtos.raw_bid_data_dto import RawBidData
from ...domain.entities.area import BidAreaChangeset
from ..dtos.create_condition_spec_dto import CreateConditionSpec
from ..dtos.insert_annotation_spec_dto import InsertAnnotationSpec
from ..dtos.insert_takeoff_spec_dto import InsertTakeoffSpec
from ..dtos.paste_ref_remap_dto import PasteRefRemap


class IMdbWriter(Protocol):
    def delete_bids(self, db_path: str, bid_uids: List[str]) -> bool: ...
    def delete_projects(self, db_path: str, project_uids: List[str]) -> bool: ...
    def create_project(self, db_path: str, name: str) -> Optional[str]: ...
    def rename_project(self, db_path: str, project_uid: str, new_name: str) -> bool: ...
    def move_bids_to_project(
        self,
        db_path: str,
        bid_uids: List[str],
        project_uid: str,
        orig_project_uid: Optional[str] = None,
    ) -> bool: ...
    def orphan_bids(self, db_path: str, bid_uids: List[str]) -> bool: ...
    def duplicate_bid(self, db_path: str, bid_uid: str) -> Optional[str]: ...
    def create_bid(
        self, db_path: str, project_uid: Optional[str], updates: Dict[str, Any]
    ) -> Optional[str]: ...
    def import_ost_data(
        self,
        db_path: str,
        raw_data: RawBidData,
        transform_fn: Callable,
        target_project_uid: Optional[str] = None,
    ) -> bool: ...
    def save_cover_sheet(
        self, db_path: str, bid_uid: str, updates: Dict[str, Any]
    ) -> bool: ...
    def update_bid_job_status(
        self, db_path: str, bid_uid: str, job_status_uid: Optional[str]
    ) -> bool: ...
    def save_job_statuses(self, db_path: str, changes: Dict[str, Any]) -> bool: ...
    def save_bid_areas(
        self, db_path: str, bid_uid: str, changes: BidAreaChangeset
    ) -> Dict[str, str]: ...
    def save_page_scale(
        self, db_path: str, page_uid: str, sf1: float, sf2: float
    ) -> bool: ...
    def save_page_name(self, db_path: str, page_uid: str, name: str) -> bool: ...
    def save_page_show_mode(
        self, db_path: str, page_uid: str, show_mode: int
    ) -> bool: ...
    def save_page_overlay_image(
        self, db_path: str, page_uid: str, overlay_image_path: str
    ) -> bool: ...
    def save_page_overlay_rect(
        self,
        db_path: str,
        page_uid: str,
        overlay_rect: Tuple[float, float, float, float],
    ) -> bool: ...
    def save_page_invert(self, db_path: str, page_uid: str, invert: bool) -> bool: ...
    def save_page_bitonal(self, db_path: str, page_uid: str, bitonal: bool) -> bool: ...
    def save_page_image_adjustments(
        self,
        db_path: str,
        page_uids: List[str],
        rotation: int,
        flip_x: bool,
        flip_y: bool,
        invert: bool,
        bitonal: bool,
    ) -> bool: ...
    def save_page_area(self, db_path: str, page_uid: str, area_uid: str) -> bool: ...
    def delete_pages(self, db_path: str, page_uids: List[str]) -> bool: ...
    def save_takeoffs_area(
        self, db_path: str, takeoff_uids: List[str], area_uid: str
    ) -> bool: ...
    def save_takeoffs_condition(
        self, db_path: str, takeoff_uids: List[str], condition_uid: str
    ) -> bool: ...
    def set_takeoffs_negative(
        self, db_path: str, takeoff_uids: List[str], is_negative: bool
    ) -> bool: ...
    def set_takeoff_curve(
        self, db_path: str, takeoff_uid: str, position: List[float], curve: int
    ) -> bool: ...
    def save_takeoff_positions(
        self, db_path: str, positions: List[Tuple[str, List[float]]]
    ) -> bool: ...
    def save_takeoff_rotations(
        self, db_path: str, rotations: List[Tuple[str, float]]
    ) -> bool: ...
    def save_takeoff_text_properties(
        self, db_path: str, updates: List[Tuple[str, Dict[str, Any]]]
    ) -> bool: ...
    def delete_takeoffs(self, db_path: str, takeoff_uids: List[str]) -> bool: ...
    def save_annotation_positions(
        self, db_path: str, positions: List[Tuple[str, str, List[float]]]
    ) -> bool: ...
    def save_annotation_text_properties(
        self, db_path: str, updates: List[Tuple[str, str, Dict[str, Any]]]
    ) -> bool: ...
    def save_annotation_styles(
        self, db_path: str, updates: List[Tuple[str, str, Dict[str, Any]]]
    ) -> bool: ...
    def insert_takeoffs(
        self,
        db_path: str,
        bid_uid: str,
        takeoff_specs: List[InsertTakeoffSpec],
    ) -> List[str]: ...
    def insert_annotations(
        self,
        db_path: str,
        bid_uid: str,
        specs: List[InsertAnnotationSpec],
        ref_remap: Optional[PasteRefRemap] = None,
    ) -> List[str]: ...
    def duplicate_conditions(
        self, db_path: str, bid_uid: str, condition_uids: List[str]
    ) -> List[str]: ...
    def duplicate_conditions_to_bid(
        self,
        db_path: str,
        source_bid_uid: str,
        destination_bid_uid: str,
        condition_uids: List[str],
    ) -> Dict[str, str]: ...
    def insert_condition(
        self, db_path: str, bid_uid: str, spec: CreateConditionSpec
    ) -> Optional[str]: ...
    def delete_conditions(
        self, db_path: str, bid_uid: str, condition_uids: List[str]
    ) -> bool: ...
    def insert_condition_folder(
        self,
        db_path: str,
        bid_uid: str,
        name: str,
        parent_uid: Optional[str] = None,
    ) -> Optional[str]: ...
    def rename_condition_folder(
        self, db_path: str, folder_uid: str, name: str
    ) -> bool: ...
    def delete_condition_folders(
        self, db_path: str, folder_uids: List[str]
    ) -> bool: ...
    def update_condition(
        self,
        db_path: str,
        bid_uid: str,
        condition_uid: str,
        updates: Any,
    ) -> bool: ...
    def renumber_conditions(
        self, db_path: str, bid_uid: str, ordered_condition_uids: List[str]
    ) -> bool: ...
    def shift_ref_nos(
        self,
        db_path: str,
        bid_uid: str,
        from_ref_no: int,
        exclude_uid: str,
    ) -> bool: ...
    def save_page_view_state(
        self,
        db_path: str,
        page_uid: str,
        zoom_fac: float,
        current_x: float,
        current_y: float,
    ) -> bool: ...
    def update_layer_show(self, db_path: str, layer_uid: str, show: bool) -> bool: ...
    def insert_layer(
        self, db_path: str, bid_uid: str, name: str, after_sequence: int
    ) -> Optional[str]: ...
    def delete_layer(self, db_path: str, layer_uid: str) -> bool: ...
    def update_all_layers_show(
        self, db_path: str, bid_uid: str, show: bool
    ) -> bool: ...
    def swap_layer_sequence(
        self, db_path: str, layer_uid_a: str, layer_uid_b: str
    ) -> bool: ...
    def update_layer_name(self, db_path: str, layer_uid: str, name: str) -> bool: ...
    def save_employees(self, db_path: str, changes: Dict[str, Any]) -> bool: ...
    def save_pay_classes(self, db_path: str, changes: Dict[str, Any]) -> bool: ...
    def save_condition_types(
        self, db_path: str, changes: Dict[str, Any]
    ) -> Optional[Dict[str, str]]: ...
    def delete_annotations(self, db_path: str, annotations: List[str]) -> bool: ...
    def save_bid_selected_page(
        self, db_path: str, bid_uid: str, page_uid: str
    ) -> bool: ...
