from typing import Any, Optional, Protocol


class IMessageNotifier(Protocol):
    def post_message(
        self, title: str, message: str, severity: str = "info"
    ) -> None: ...
    def set_parent(self, parent: Optional[Any]) -> None: ...
    def set_update_active(self, active: bool) -> None: ...
    def cleanup(self) -> None: ...
