from typing import Any, Callable, Optional, Protocol


class ITransactionMonitor(Protocol):
    def is_monitoring(self) -> bool: ...
    def is_ost_active(self) -> bool: ...
    def start_monitoring(self, callback: Callable[[], None]) -> bool: ...
    def stop_monitoring(self) -> None: ...
    def cleanup(self) -> None: ...
    def set_update_dialog_active(self, active: bool) -> None: ...
    def set_message_parent(self, parent: Optional[Any]) -> None: ...
    def set_ost_status_callback(self, callback: Callable[[bool], None]) -> None: ...
