from typing import Dict, Optional, Protocol, runtime_checkable
from ..dtos.raw_bid_data_dto import RawBidData
from ..entities.file_results import BidLoadResult, FileLoadResult


@runtime_checkable
class IFileParser(Protocol):
    def parse(self, file_path: str) -> FileLoadResult: ...
    def load_bid_data(self, file_path: str, bid_uid: str) -> BidLoadResult: ...
    def get_database_statistics(self, file_path: str) -> Dict[str, int]: ...
    def get_raw_bid_data(self, file_path: str, bid_uid: str) -> RawBidData: ...
    def close_connection(self, file_path: Optional[str] = None) -> None: ...
