from typing import Dict, Optional, Protocol
from ..dtos.raw_bid_data_dto import RawBidData
from ..entities.file_results import BidLoadResult, FileLoadResult
from ..entities.layer import BidLayer


class IFileParser(Protocol):
    def parse(self, file_path: str) -> FileLoadResult: ...
    def load_bid_data(self, file_path: str, bid_uid: str) -> BidLoadResult: ...
    def get_bid_layers_for_sidebar(
        self, file_path: str, bid_uid: str
    ) -> list[BidLayer]: ...
    def get_database_statistics(self, file_path: str) -> Dict[str, int]: ...
    def get_raw_bid_data(self, file_path: str, bid_uid: str) -> RawBidData: ...
    def close_connection(self, file_path: Optional[str] = None) -> None: ...
