from typing import Dict, Optional, Protocol
from ..entities.cdn_type import CdnType
from ..entities.file_results import BidLoadResult, FileLoadResult
from ..entities.hierarchy_data import HierarchyData, HierarchyFileEntry


class IProjectRepository(Protocol):
    @property
    def active_file_path(self) -> Optional[str]: ...
    @property
    def current_hierarchy_data(self) -> HierarchyData: ...
    def load_file(self, file_path: str) -> FileLoadResult: ...
    def register_loaded_hierarchy(
        self,
        file_entry: HierarchyFileEntry,
        cdn_types: Dict[str, CdnType],
    ) -> HierarchyData: ...
    def unload_file(self, file_path: Optional[str] = None) -> bool: ...
    def load_bid(
        self, bid_uid: str, file_path: Optional[str] = None
    ) -> BidLoadResult: ...
    def reload_database(self, file_path: Optional[str] = None) -> FileLoadResult: ...
    def get_merged_cdn_types(self) -> Dict[str, CdnType]: ...
